### ISSUE TITLE
Support version `latest`

### ISSUE THREAD

**Issue by tumf** [tumf/ansible-role-docker-compose#2]
Support `docker_compose_version: latest`.

To get latest version's tag name is as below:

``` shell
version=$(curl https://api.github.com/repos/docker/compose/releases/latest 2>/dev/null |jq '.tag_name' -r)
```

**Comment by eddyhub** [comment]
Hi,
I implemented a possible solution: https://github.com/tumf/ansible-role-docker-compose/pull/3

**Comment by tumf** [comment]
Thank you.I'm working for merge.
